name: CarolineDoumengPhotography
favicon: null
layout_spectrum: 0.27949411468580365
typography_spectrum: 0.040754511719569564
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6365229252260178
  lightness: 0.47375737223774195
  saturation: 0.975654210196808
  rhythmicContrast: 0.045245484448969364
purpose: []
